# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abilities',
            new_name='Ability',
        ),
    ]
