# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_player_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('date', 'team', 'opponent')]),
        ),
    ]
