# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_auto_20160528_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Player')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.Position')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([('game', 'inning', 'player'), ('game', 'inning', 'position')]),
        ),
    ]
